[package]
name = "llm_wasm"
version = "0.1.0"
authors = ["rcanfield <Rcanfield86@gmail.com>"]
edition = "2021"

[lib]
name = "llm_wasm"
crate-type = ["dylib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
